### ISSUE TITLE
YELP dataset version

### ISSUE THREAD

**Issue by domenicodegioia** [tanatosuu/svd_gcn#2]
which version of YELP dataset did you use for your work?

**Comment by tanatosuu** [comment]
Thanks for your question. Please find the dataset in the "datasets" file. The Yelp data used in our work is from [1]. It seems that it is from Yelp challenge 2015. Please refer to the data description of Yelp in [1].
[1] Fast Matrix Factorization for Online Recommendation with Implicit Feedback
